theme: jekyll-theme-midnight
title: "Team Orb Orb Car Dealership"
description: "Team Orb Orb's Dealership in period 4 Mort"
gitorg: "https://github.com/TeamORBORB/OrbOrb-Reunion"
description: "Luxury and everyday cars at amazing prices!"
google_analytics:
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one