theme: jekyll-theme-midnight
title: "Team Orb Orb Reunion"
description: "Team Orb Orb's reunion in period 4 Mort"
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "Jan 3 2023 - Infinity"
google_analytics:
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one